### PR TITLE
Delete everything

### PR DESCRIPTION
**Pull request by tjcrone**

### CODE REVIEW

**Comment by tjcrone** [comment]
Prepping this repo for the new book content.

**Comment by rabernat** [comment]
I'm not sure this is necessary since I think the [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) will probably overwrite it anyway. And in the meantime, **the book site will go down**. So I would prefer to wait until we have the new build process in place to delete this. Does that make sense?

**Comment by tjcrone** [comment]
Are you sure the new actions will delete all of the content that is there? The structure of the site will be much different so lots of stuff will not be overwritten. I was only expecting the book to be down for a minute or two since the other system is ready to post. But if you would rather do this incrementally I should be able to make it work.

**Comment by rabernat** [comment]
> Are you sure the new actions will delete all of the content that is there?

No

> I was only expecting the book to be down for a minute or two since the other system is ready to post

Ok, I didn't know this because you didn't say it until now. I didn't know whether the site would be down for days. Obviously two minutes downtime is fine.

There was no need to close the PR. I just wanted to discuss.

**Comment by tjcrone** [comment]
I convinced myself that we can do an overwrite and then clean up afterwards. I think that is probably better.

**Pull request closed without merging**
